version: '2'
services:
  web2:
    build: .
    command: bash -c 'while !</dev/tcp/mongo/27017; do sleep 1; done; npm run start' # wait while postgres is not up
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /data/db
